setwd('~/Desktop/rezoner')
rm(list = ls())
gc()
source('~/Desktop/rezoner/merge_scenario_d.R', local=F)
rm(list = ls())
gc()
source('~/Desktop/rezoner/preprocessing.R', local=F)
rm(list = ls())
gc()
source('~/Desktop/rezoner/filter_out_extraneous.R', local=F)
rm(list = ls())
gc()
source('~/Desktop/rezoner/to_mapbox.R', local=F)
rm(list = ls())
